sonar.organization=sitionix-vv
sonar.projectKey=sitionix_sitionix-spa
sonar.projectName=sitionix-spa

sonar.sources=apps,packages
sonar.tests=apps,packages
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.int.test.ts,**/*.int.test.tsx,**/src/test/**
sonar.javascript.lcov.reportPaths=apps/**/coverage/lcov.info,packages/**/coverage/lcov.info
sonar.exclusions=**/dist/**,**/node_modules/**,**/coverage/**,**/build/**,**/*.md,**/*.txt
sonar.coverage.exclusions=**/vite.config.*,**/vitest.config.*,**/postcss.config.*,**/tailwind.config.*,**/mf/**,**/public/**,**/src/main.*,**/src/app/App.tsx,**/src/app/router.tsx,**/src/features/dashboard/ui/DashboardPage.tsx,**/src/features/workspace/modules/automation/pages/AgentOverviewPage.tsx,**/src/features/workspace/modules/automation/pages/ProjectFlowPage.tsx,**/src/features/workspace/modules/automation/pages/AgentProjectDetailsPage.tsx,**/src/features/workspace/modules/automation/api/agentsApi.ts,**/src/features/workspace/modules/automation/model/types.ts
