sonar.organization=sitionix-vv
sonar.projectKey=sitionix_sitionix-spa
sonar.projectName=sitionix-spa

sonar.sources=apps,packages
sonar.tests=apps,packages
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.int.test.ts,**/*.int.test.tsx
sonar.javascript.lcov.reportPaths=apps/**/coverage/lcov.info,packages/**/coverage/lcov.info
sonar.exclusions=**/dist/**,**/node_modules/**,**/coverage/**,**/build/**,**/*.md,**/*.txt
